### ISSUE TITLE
Not a source file, it's a release.

### ISSUE THREAD

**Issue by biggestsonicfan** [batocera-linux/model2emu#1]
Github is not a file hosting service. Your zip contains a binary release of the model2 emulator. Labeling it as a "Source file" is very misleading.

**Comment by nadenislamarre** [comment]
where ?

**Comment by nadenislamarre** [comment]
it is not a release, just a binary.
it is not labeled source code, just source.
not sure we need to take time to debate about such wording.

**Comment by biggestsonicfan** [comment]
It is a "release" of the Model2 emulator. It is a compressed archive, not a "binary", it has binaries within it as well as other files. Again, github is not a place for a "repo" to host "binaries". That is for a hosting service to do. There's no reason for this repo to exist other than to abuse github as a hosting service.

EDIT: You may be using it as a "source" for other software to reverence, as in "This is the source of the data", but once more, github is not your personal file hosting service.
